# Branch protection rules for main branch
# This ensures automerge works properly with Dependabot

branches:
  - name: "main"
    protection:
      required_status_checks:
        strict: true
        contexts:
          - "test-and-build"
      enforce_admins: false
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: false
        # Allow Dependabot to bypass branch protection for automerge
        bypass_pull_request_allowances:
          users:
            - "dependabot[bot]"
      restrictions:
        users: []
        teams: []
      allow_force_pushes: false
      allow_deletions: false
      block_creations: false
      required_conversation_resolution: true
      # Allow automerge for Dependabot PRs
      allow_auto_merge: true
